spring.application.name=demo
spring.application.port=7070
# MySQL Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/erb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:erbuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:ayman@123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Logging
logging.level.root=INFO
logging.level.com.erb.demo=DEBUG
logging.file.name=logs/app.log

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ayman.aljamal2017@gmail.com
spring.mail.password=bfff nxci iavw bidm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true


management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
# management.endpoints.web.base-path=/manage
info.app.name=My Spring Boot App
info.app.version=1.0.0
info.company.name=ayman Inc.



exchange.api.key=137494a705de91f3b2b2f880
exchange.api.url=https://v6.exchangerate-api.com/v6


spring.graphql.graphiql.enabled=true
